### ISSUE TITLE
commit  f54581cad5289ef753a5 oddity on rebuild patch

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#31]
Sativarg added a note to f54581c

about 13 hours ago

Not sure what happened

File "D:\Fallout New Vegas\Mopy\basher.py", line 4946, in Execute

raise

File "D:\Fallout New Vegas\Mopy\basher.py", line 4897, in Execute

patchFile = bosh.PatchFile(self.patchInfo,patchers)

File "D:\Fallout New Vegas\Mopy\bosh.py", line 16252, in init

patcher.initPatchFile(self,self.loadMods)

File "D:\Fallout New Vegas\Mopy\bosh.py", line 16985, in initPatchFile

for recClass in (MreRepu):

TypeError: iteration over non-sequence
Traceback (most recent call last):
File "D:\Fallout New Vegas\Mopy\basher.py", line 4946, in Execute

raise

File "D:\Fallout New Vegas\Mopy\basher.py", line 4897, in Execute

patchFile = bosh.PatchFile(self.patchInfo,patchers)

File "D:\Fallout New Vegas\Mopy\bosh.py", line 16252, in init

patcher.initPatchFile(self,self.loadMods)

File "D:\Fallout New Vegas\Mopy\bosh.py", line 16985, in initPatchFile

for recClass in (MreRepu):

TypeError: iteration over non-sequence

**Comment by valda** [comment]
it fixed at 86738d108429c5126c205a1bd104f27c907fa91c
thanks!

**Comment by Sativarg** [comment]
Thank you
