### ISSUE TITLE
Building patch fatal error after updating to 2945f9c

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#32]
Building patch fatal error after updating to 2945f9c

Loading: 0017AFB7..ExtDesertNorthVegas..ASPC.WNAM..4..
Traceback (most recent call last):
  File "E:\Fallout New Vegas\Mopy\basher.py", line 4946, in Execute
    raise
  File "E:\Fallout New Vegas\Mopy\basher.py", line 4898, in Execute
    patchFile.initData(SubProgress(progress,0,0.1)) #try to speed this up!
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 16543, in initData
    patcher.initData(SubProgress(progress,index))
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 17321, in initData
    masterFile.load(True)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 7103, in load
    self.tops[label].load(ins,unpack and (topClass != MobBase))
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 6112, in load
    self.loadData(ins, ins.tell()+self.size-recHeaderSize)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 6214, in loadData
    record = recClass(header,ins,True)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1873, in **init**
    self.**class**.melSet.initRecord(self,header,ins,unpack)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1452, in initRecord
    MreRecord.**init**(record,header,ins,unpack)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1670, in **init**
    if ins: self.load(ins,unpack)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1733, in load
    self.loadData(ins,inPos+self.size)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1882, in loadData
    self.**class**.melSet.loadData(self,ins,endPos)
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1486, in loadData
    raise
  File "E:\Fallout New Vegas\Mopy\bosh.py", line 1476, in loadData
    raise ModError(ins.inName,_('Unexpected subrecord: ')+readId)
bosh.ModError: FalloutNV.esm: Unexpected subrecord: ASPC.WNAM

**Comment by Sativarg** [comment]
Fixed thanks
