### ISSUE TITLE
Problem when making bashed patch. . .

### ISSUE THREAD

**Issue by ebeneezersquid** [valda/garybash#37]
Running Python 2.7 and wxpython 2.8 and am getting the following bugdump when I rebuild a patch. Got Something similar back on v12, went away on v13, now on v14.4 it is back.

(
Loading: 00175D6C..vHDPowerPlant01toOffices01..REFR.XTEL..32..
Error in FalloutNV.esm
Traceback (most recent call last):
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Basher.py", line 5836, in Execute
patchFile.scanLoadMods(SubProgress(progress,0.2,0.8)) #try to speed this up!
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 20374, in scanLoadMods
modFile.load(True,SubProgress(progress,index,index+0.5))
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 7374, in load
records.load(ins,unpack and (topClass != MobBase))
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6348, in load
self.loadData(ins, ins.tell()+self.size-recHeaderSize)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6982, in loadData
cellBlock = MobCell(header,selfLoadFactory,cell,ins,True)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6626, in **init**
MobBase.**init**(self,header,loadFactory,ins,unpack)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6338, in **init**
if ins: self.load(ins,unpack)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6348, in load
self.loadData(ins, ins.tell()+self.size-recHeaderSize)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 6657, in loadData
record = recClass(header,ins,True)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1942, in **init**
self.**class**.melSet.initRecord(self,header,ins,unpack)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1522, in initRecord
MreRecord.**init**(record,header,ins,unpack)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1740, in **init**
if ins: self.load(ins,unpack)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1803, in load
self.loadData(ins,inPos+self.size)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1951, in loadData
self.**class**.melSet.loadData(self,ins,endPos)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1551, in loadData
loaders[type].loadData(record,ins,type,size,readId)
File "G:\Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 1086, in loadData
unpacked = ins.unpack(self.format,size,readId)
File "G:Steam\steamapps\common\fallout new vegas\Mopy\Bash\Bosh.py", line 545, in unpack
return struct.unpack(format,self.ins.read(size))
struct.error: unpack requires a string argument of length 28
)

Some instability, and numerous tweaks that should be incorporated into the bashed patch don't appear to have been included (inventory sorting, etc).

**Comment by valda** [comment]
Thanks for your bug report.
Because I fixed it, please try the latest version if you don't mind.

https://github.com/valda/garybash/commit/b1ed41b7f4ec7ba4bf9de75ff2618fc2b686b6c1
