### ISSUE TITLE
Fallout3.exe not found 

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#39]
Using the batch file to troubleshoot valda-garybash-RELEASE_30_3-1-ga3139da.zip I get "Failed to find Fallout3.exe in C:\steam\steamapps\common\Fallout New Vegas."

I downloaded this file from the Fallout New Vegas branch so I figured it would work in the folder
C:\steam\steamapps\common\Fallout New Vegas

It does not run when clicking C:\steam\steamapps\common\Fallout New Vegas\Mopy\Wrye Bash Launcher.pyw

a text search of all the PY files for the word "FalloutNV.exe" has zero result but Fallout3.exe returns 9 files so I am betteing this is not the correct version to run for New Vegas.

Traceback (most recent call last):
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 375, in <module>    main()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 294, in main
    bosh.initBosh(opts.personalPath,opts.localAppDataPath,opts.falloutPath)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 35866, in initBosh    initDirs(bashIni,personal,localAppData, falloutPath)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 35608, in initDirs
    dirs['app'] = getFalloutPath(bashIni,falloutPath)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 35519, in getFalloutPath
    raise BoltError(_("Install Error\nFailed to find Fallout3.exe in %s.\nNote t
hat the Mopy folder should be in the same folder as Fallout3.exe.") % path)
bolt.BoltError: Install Error
Failed to find Fallout3.exe in C:\steam\steamapps\common\Fallout New Vegas.
Note that the Mopy folder should be in the same folder as Fallout3.exe.

C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash>

UPDATE: made fake files to satisfy "missing Fallout3 content did no good
bosh.py 11606 **init**: Using BOSS API version: 2.1.0
bosh.py 11606 **init**: Using BOSS API version: 2.1.0
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 32, in <module>
    bash.main()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 361, in main
    app.Init()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 5484, in Init
    self.InitData(progress)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 5518, in InitData
    bosh.modInfos.refresh(doAutoGroup=True)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 10502, in refresh
    self.getFalloutVersions()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 11182, in getFalloutVersions
    self.voCurrent = self.size_voVersion.get(self.data[self.masterName].size,None)
KeyError: bolt.Path('Fallout3.esm')

**Comment by Sativarg** [comment]
UPDATE: I was using the wrong tab/button to download...
Downloads · valda/garybash - https://github.com/valda/garybash/downloads
the downloads tab zip yields this :valda-garybash-RELEASE_30_3-1-ga3139da.zip
ZIP - https://github.com/valda/garybash/zipball/master
The button ZIP yields: valda-garybash-NV_15_4-0-g62f6224.zip
