### ISSUE TITLE
checkbox_purple_on.png not in missing folder?

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#40]
C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash>bash.py
Traceback (most recent call last):
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 375
, in <module>
    main()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 305
, in main
    import basher
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 4
61, in <module>
    colorChecks = ColorChecks()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 4
25, in **init**
    image = images[imageKey] = Image(file,wx.BITMAP_TYPE_PNG)
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\balt.py", line 125
, in **init**
    raise ArgumentError(_("Missing resource file: %s.") % (self.file,))
bolt.ArgumentError: Missing resource file: C:\steam\steamapps\common\Fallout New
 Vegas\Mopy\bash\bash\images\checkbox_purple_on.png.

No such folder "Mopy\bash\bash\images\"

**Comment by Sativarg** [comment]
UPDATE: I was using the wrong tab/button to download...
Downloads · valda/garybash - https://github.com/valda/garybash/downloads
the downloads tab zip yields this :valda-garybash-RELEASE_30_3-1-ga3139da.zip
ZIP - https://github.com/valda/garybash/zipball/master
The button ZIP yields: valda-garybash-NV_15_4-0-g62f6224.zip
