### ISSUE TITLE
BOSS_API_ERROR_FILE_NOT_FOUND:"Fallout3.esm" cannot be found!

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#41]
I copied all folders in\bash\ to a new folder C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash so I could test further and found...

Traceback (most recent call last):
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 375, in <module>
    main()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bash.py", line 334, in main
    basher.InitLinks()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 15561, in InitLinks
    InitStatusBar()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\basher.py", line 14614, in InitStatusBar
    configHelpers = bosh.ConfigHelpers()
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bosh.py", line 11605, in **init**
    boss = bapi.BossDb(GPath(dirs['app'].s).s,'Fallout 3')
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bapi.py", line 359, in **init**
    _CCreateBossDb(byref(self._DB),game,_enc(gamePath))
  File "C:\steam\steamapps\common\Fallout New Vegas\Mopy\bash\bapi.py", line 226, in BossErrorCheck
    raise BossError(result)
bapi.BossError: BossError: BOSS_API_ERROR_FILE_NOT_FOUND:"Fallout3.esm" cannot be found!

**Comment by Sativarg** [comment]
UPDATE: I was using the wrong tab/button to download...
Downloads · valda/garybash - https://github.com/valda/garybash/downloads
the downloads tab zip yields this :valda-garybash-RELEASE_30_3-1-ga3139da.zip
ZIP - https://github.com/valda/garybash/zipball/master
The button ZIP yields: valda-garybash-NV_15_4-0-g62f6224.zip
